# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubbly < Formula
  desc "Bubbly CLI"
  homepage "https://bubbly.dev/"
  version "0.0.1-alpha.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_darwin_amd64.tar.gz"
    sha256 "0ee2a9a07e73446cce2eb3fd03ae54af45d69ae04d2a8fd1abf47978ca62f9b9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_darwin_arm64.tar.gz"
    sha256 "565c0159af2b4f32ef242cbff01a4864de95083d84babe72e39bdd726ba5c6bb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_linux_amd64.tar.gz"
    sha256 "9f448117735bf6eca98579ab0f915c8793e6323c6d24ff87fb0d173fd8b9a7e3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_linux_arm64.tar.gz"
    sha256 "20783ec711eac6cb5b3eb50cafbffa43ab7adbc64c26445c81d9f8b29bd1c20c"
  end

  depends_on "go"

  def install
    bin.install "bubbly"
  end

  test do
    system "#{bin}/bubbly --version"
  end
end
