# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubbly < Formula
  desc "Bubbly CLI"
  homepage "https://bubbly.dev/"
  version "0.0.1-alpha.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_darwin_amd64.tar.gz"
    sha256 "bac271f27ab8194033c08c65dc5a1d279be99326fa71c208f6f805373f514e08"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_darwin_arm64.tar.gz"
    sha256 "4033cbd73636c3e761e3685fe18b7e0acb99a952a0c28e52e661e525c2b916b1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_linux_amd64.tar.gz"
    sha256 "bab6ecb2ff362dd385fc85094db9fce39a69f42ab50fe15badb72b8c5d1fc743"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/verifa/bubbly/releases/download/v0.0.1-alpha.2/bubbly_0.0.1-alpha.2_linux_arm64.tar.gz"
    sha256 "6f18db4b7fb3afae3833c982abec18a2c7dd3476a0a9894a57340ebb14a3bb67"
  end

  depends_on "go"

  def install
    bin.install "bubbly"
  end

  test do
    system "#{bin}/bubbly --version"
  end
end
