# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coastline < Formula
  desc "Terraplate"
  homepage "https://github.com/verifa/coastline"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/verifa/coastline/releases/download/v0.0.6/coastline_0.0.6_darwin_arm64.tar.gz"
      sha256 "9a0418b2f9226ffab0ba6eb4520e79ebfb457b9a1074fcbfc0dc509999f4c346"

      def install
        bin.install "coastline"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/coastline/releases/download/v0.0.6/coastline_0.0.6_darwin_amd64.tar.gz"
      sha256 "d535dbf55e59b65491e78f1f4d7f57500fe5a95b959f841433c26f8368e10b2b"

      def install
        bin.install "coastline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/verifa/coastline/releases/download/v0.0.6/coastline_0.0.6_linux_amd64.tar.gz"
      sha256 "bb20535b256826e9aef5ab03cdae5029071325d4b8dc81b96f2fa2467952cfd4"

      def install
        bin.install "coastline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/coastline/releases/download/v0.0.6/coastline_0.0.6_linux_arm64.tar.gz"
      sha256 "2ec5f11a16d8be5c5a1d428fec1205732a76abd29889a2d120f301efd51493e6"

      def install
        bin.install "coastline"
      end
    end
  end

  test do
    system "#{bin}/coastline version"
  end
end
