# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coastline < Formula
  desc "Terraplate"
  homepage "https://github.com/verifa/coastline"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/verifa/coastline/releases/download/v0.0.7/coastline_0.0.7_darwin_arm64.tar.gz"
      sha256 "692bef1594ab0134b6cc5c812ab6e2116ba32ce86de680da724f03386cee39c7"

      def install
        bin.install "coastline"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/coastline/releases/download/v0.0.7/coastline_0.0.7_darwin_amd64.tar.gz"
      sha256 "5d427f206b8200ec59ae44257d0863c528dcdfaa5c7c10dbf1447e6406cbc0bb"

      def install
        bin.install "coastline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/coastline/releases/download/v0.0.7/coastline_0.0.7_linux_arm64.tar.gz"
      sha256 "1564addf45572bc03a877b0268b2098431d1fb640b6fc942a2e3fb73f029cef9"

      def install
        bin.install "coastline"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/coastline/releases/download/v0.0.7/coastline_0.0.7_linux_amd64.tar.gz"
      sha256 "5660eb67ce12bd8c7f319fd086bb3d62d9e79e3c583ac000b5bc9e59928ea437"

      def install
        bin.install "coastline"
      end
    end
  end

  test do
    system "#{bin}/coastline version"
  end
end
