# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpEcho < Formula
  desc "http-echo"
  homepage "https://github.com/verifa/http-echo"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verifa/http-echo/releases/download/0.3.1/http-echo_0.3.1_darwin_amd64.tar.gz"
      sha256 "5cf48cef8bed416f3982b0c32b09d790848f9f3b7d325c92e6fdf3bde945268f"

      def install
        bin.install "http-echo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verifa/http-echo/releases/download/0.3.1/http-echo_0.3.1_darwin_arm64.tar.gz"
      sha256 "a7ed968deb8378af807768b6935702a6524485958044cf8559c9195b99d77a86"

      def install
        bin.install "http-echo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/http-echo/releases/download/0.3.1/http-echo_0.3.1_linux_arm64.tar.gz"
      sha256 "a3051c01fb8e924001b1d2c50d553dafa7c172fd9999fb3e743ec275313e6b54"

      def install
        bin.install "http-echo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/http-echo/releases/download/0.3.1/http-echo_0.3.1_linux_amd64.tar.gz"
      sha256 "aee003a656605ff75c2de5234cea2178ac111f923dae66def71c878d0b167895"

      def install
        bin.install "http-echo"
      end
    end
  end

  test do
    system "#{bin}/http-echo --version"
  end
end
