# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpEcho < Formula
  desc "http-echo"
  homepage "https://github.com/verifa/http-echo"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/verifa/http-echo/releases/download/0.3.0/http-echo_0.3.0_darwin_arm64.tar.gz"
      sha256 "253255024bef05f616cd3fbd6f810c55ad0e62a7524d83430782419cfae4199e"

      def install
        bin.install "http-echo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/http-echo/releases/download/0.3.0/http-echo_0.3.0_darwin_amd64.tar.gz"
      sha256 "9fd78231dd419bd28084ca6cdd96e6ba598ce45226b6d2a7755f42603d27bdd3"

      def install
        bin.install "http-echo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/http-echo/releases/download/0.3.0/http-echo_0.3.0_linux_arm64.tar.gz"
      sha256 "89ab9b06efc810c0625849618afa516d656a2de05a15b14c770127a00a4b4d65"

      def install
        bin.install "http-echo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/http-echo/releases/download/0.3.0/http-echo_0.3.0_linux_amd64.tar.gz"
      sha256 "b05bc458e5b99eeb7f5019a581c581585c1f10429250c587b0eaa74b31e8a547"

      def install
        bin.install "http-echo"
      end
    end
  end

  test do
    system "#{bin}/http-echo --version"
  end
end
