# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RtRetention < Formula
  desc "Artifactory Retention"
  homepage "https://github.com/verifa/rt-retention"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.3/rt-retention_0.0.3_darwin_amd64.tar.gz"
      sha256 "8c17718bd8e0415ab1b7354e09ee7d9fbdb606355d77e98598ada15ccdd1c88a"

      def install
        bin.install "rt-retention"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.3/rt-retention_0.0.3_darwin_arm64.tar.gz"
      sha256 "81a87740e3a85563297230a34b2052426fa03519eefbe7390671a885255b36b3"

      def install
        bin.install "rt-retention"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.3/rt-retention_0.0.3_linux_arm64.tar.gz"
      sha256 "9e6285530f999da0b7fbdeb7b6dfdf421f66ea62c6d5fa48064d22ccdab1fbc9"

      def install
        bin.install "rt-retention"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.3/rt-retention_0.0.3_linux_amd64.tar.gz"
      sha256 "dba6ca381ad81370c14e8c1c00daa0b35285a4f98c0c9dbcd0a4ced7b55b41ff"

      def install
        bin.install "rt-retention"
      end
    end
  end

  test do
    system "#{bin}/rt-retention -v"
  end
end
