# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RtRetention < Formula
  desc "Artifactory Retention"
  homepage "https://github.com/verifa/rt-retention"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.4/rt-retention_0.0.4_darwin_arm64.tar.gz"
      sha256 "ab2bc03071330f73b93037f76436353f7ae5463a10de276376ec33c90dc2da2f"

      def install
        bin.install "rt-retention"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.4/rt-retention_0.0.4_darwin_amd64.tar.gz"
      sha256 "570dab50311ac08dc0ea356babe3212334bec657c9bb2bb4f03fb3db4d112935"

      def install
        bin.install "rt-retention"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.4/rt-retention_0.0.4_linux_amd64.tar.gz"
      sha256 "a46cf76d77bb88b5c58fde5019a999369e1cbf497a897ab51de38da6424dc542"

      def install
        bin.install "rt-retention"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/rt-retention/releases/download/v0.0.4/rt-retention_0.0.4_linux_arm64.tar.gz"
      sha256 "19710ed77590712aa007e56867b21b9bc2ca246bb5fd7a88e6f6f606fe2ff05e"

      def install
        bin.install "rt-retention"
      end
    end
  end

  test do
    system "#{bin}/rt-retention -v"
  end
end
