# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraplate < Formula
  desc "Terraplate"
  homepage "https://github.com/verifa/terraplate"
  version "0.2.1-alpha"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/verifa/terraplate/releases/download/0.2.1-alpha/terraplate_0.2.1-alpha_darwin_arm64.tar.gz"
      sha256 "13eeeb67152eb9edc355e661c1c69f59c49cb09422c14d4dcaaa3a5783a88642"

      def install
        bin.install "terraplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/terraplate/releases/download/0.2.1-alpha/terraplate_0.2.1-alpha_darwin_amd64.tar.gz"
      sha256 "c7c287520f8fdbeee85560f12812a2a05431cc7137afe69effe75b5881fefd7e"

      def install
        bin.install "terraplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/terraplate/releases/download/0.2.1-alpha/terraplate_0.2.1-alpha_linux_arm64.tar.gz"
      sha256 "3c2b33616a72dd3cd3f6f91373c2a3ceda5a024720d83c77f6cb34a1de050fee"

      def install
        bin.install "terraplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/terraplate/releases/download/0.2.1-alpha/terraplate_0.2.1-alpha_linux_amd64.tar.gz"
      sha256 "8280850368d65438c351b71a4c6c8ac4986376a6a6274de20879526f6659f4d2"

      def install
        bin.install "terraplate"
      end
    end
  end

  test do
    system "#{bin}/terraplate version"
  end
end
