# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraplate < Formula
  desc "Terraplate"
  homepage "https://github.com/verifa/terraplate"
  version "0.0.7-alpha"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/verifa/terraplate/releases/download/0.0.7-alpha/terraplate_0.0.7-alpha_darwin_arm64.tar.gz"
      sha256 "f1a0e6da476f7c7e19f45d99d1ccb612bc1c7cd693d164b107344d607afd2348"

      def install
        bin.install "terraplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/terraplate/releases/download/0.0.7-alpha/terraplate_0.0.7-alpha_darwin_amd64.tar.gz"
      sha256 "059199d1d9671620c19d155ba30eb71a8df0a59c7da8669bbfdecb9211fab824"

      def install
        bin.install "terraplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verifa/terraplate/releases/download/0.0.7-alpha/terraplate_0.0.7-alpha_linux_arm64.tar.gz"
      sha256 "7bd077d3d04b54886cfb60adf7b003fb20c01fbcca19a9a8aa04cc1a0d389a4c"

      def install
        bin.install "terraplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/verifa/terraplate/releases/download/0.0.7-alpha/terraplate_0.0.7-alpha_linux_amd64.tar.gz"
      sha256 "61ebf025992bb893d629885160c4cf1c8174ea2b991d5e432e1e8d25a0708d04"

      def install
        bin.install "terraplate"
      end
    end
  end

  test do
    system "#{bin}/bubbly --version"
  end
end
